#!/usr/bin/env bash

if [[ ! -d /tmp/workspace/job1 ]] ;then
  mkdir -p /tmp/workspace/job1 
else
  cd /tmp/workspace || exit 1
  NR_OF_SUBFOLDERS=$(find . |  wc -l ) 
  NEW_SUBFOLDER=$(( "${NR_OF_SUBFOLDERS}" - 1))
  mv job1 "${NEW_SUBFOLDER}"_job1  &&  mkdir -p /tmp/workspace/job1 
fi 

echo "/tmp/workspace/job1 was successfully created!" 
