package bio

import bash4s.domain._
import bio.biomodel.BiologyFilePath

object biomodel {

sealed trait BioModel
final case class Cores(nrOfCores: Int) extends BioModel
final case class Sample(name: String) extends BioModel

object BioModel {
  import bash4s.dsl._
  implicit def bioToCommandOp: BioModel => CommandOp =  {
    case b: BiologyFileType[Any] => b match {
      case BiologyFilePath(fileType) => fileType
    }
    case Cores(i) => IntVariable(i)
    case Sample(name) => txt"$name"
  }
}
  type BamSorted = BiologyFileType[BamFile with Sorted]
  type BamSortedIndexed = BiologyFileType[BamFile with Sorted with Indexed]
  type FastqGz = BiologyFileType[Fastq with Gz]
//  type FastaBwaIndexed = BiologyFileType[Fasta with BwaIndexed]
  type MarkdupMetrics = BiologyFileType[Markdup with Metrics]


  sealed trait BiologyFileTypeMark extends Product with Serializable
  sealed trait BamFile extends BiologyFileTypeMark
  sealed trait VcfFile extends BiologyFileTypeMark
  sealed trait PedigreeFile extends BiologyFileTypeMark
  sealed trait G extends BiologyFileTypeMark
  sealed trait Bed extends BiologyFileTypeMark
  sealed trait FastaFile extends BiologyFileTypeMark
  sealed trait Fastq extends BiologyFileTypeMark
  sealed trait BwaIndexed extends BiologyFileTypeMark
  sealed trait DictFile extends BiologyFileTypeMark
  sealed trait Tar extends BiologyFileTypeMark
  sealed trait Txt extends BiologyFileTypeMark
  sealed trait Indexed extends BiologyFileTypeMark
  sealed trait Sorted extends BiologyFileTypeMark
  sealed trait Markdup extends BiologyFileTypeMark
  sealed trait Tbi extends BiologyFileTypeMark
  sealed trait Gz extends BiologyFileTypeMark
  sealed trait Metrics extends BiologyFileTypeMark
  // Generated by GATK4, CNNScoreVariants 
  sealed trait CnnScored_2D extends BiologyFileTypeMark

  sealed trait BiologyFileType[+T] extends BioModel {
    def e[T2]: String => BiologyFileType[T2]
    def bam = e[T with BamFile]("bam")
    def vcf = e[T with VcfFile]("vcf")
    def g = e[T with G]("g")
    def bed = e[T with Bed]("bed")
    def fasta = e[T with bio.dsl.Fasta]("fasta")
    def fastq = e[T with Fastq]("fastq")
    def bwaIndexed = e[T with BwaIndexed]("bwaIndexed")
    def tar = e[T with Tar]("tar")
    def ped = e[T with PedigreeFile]("tar")
    def txt = e[T with Txt]("txt")
    def indexed = e[T with Indexed]("indexed")
    def sorted = e[T with Sorted]("sorted")
    def markdup = e[T with Markdup]("markdup")
    def tbi = e[T with Tbi]("tbi")
    def gz = e[T with Gz]("gz")
    def metrics = e[T with Metrics]("metrics")
  }

  final case class BiologyFilePath[T](
    fileType: FileHandle
  ) extends BiologyFileType[T] { self =>

    def e[T2]: String => BiologyFilePath[T2] =
      s =>
        self.fileType match {
          case f: FileName => copy( fileType = f.copy(extension = f.extension :+ s))
          case f: RelPath => copy( fileType = f.copy(fileName = f.fileName.copy(extension = f.fileName.extension :+ s)))
          case f: FilePath => copy(fileType = f.copy(fileName = f.fileName.copy(extension = f.fileName.extension :+ s)))
          case _ => copy(fileType = fileType)
        }

  }

  object BiologyFilePath {
    
    implicit def toCommandOp[T]: BiologyFilePath[T] => CommandOp = _.fileType

  }

  object BiologyFileType extends BiologyFileType[Any] {
    implicit def toCommandOp[T]: BiologyFileType[T] => CommandOp = {
      case BiologyFilePath(
        fileType
      ) => fileType
    }
  }

}